// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmQzY3LkshtV3eZ1a8rvUnzoxS88HAeww',
    appId: '1:873225854411:web:f7abde30da50d43394ea4e',
    messagingSenderId: '873225854411',
    projectId: 'dorun-server',
    authDomain: 'dorun-server.firebaseapp.com',
    databaseURL: 'https://dorun-server-default-rtdb.firebaseio.com',
    storageBucket: 'dorun-server.appspot.com',
    measurementId: 'G-Q30TDXNQ8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL76SZoifooSDm6t3fhmjSYftmt2U0lFc',
    appId: '1:873225854411:android:5034ca34eef096df94ea4e',
    messagingSenderId: '873225854411',
    projectId: 'dorun-server',
    databaseURL: 'https://dorun-server-default-rtdb.firebaseio.com',
    storageBucket: 'dorun-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-ugZV8C1Rq7GbSlrETdNFhA2T4iv02E',
    appId: '1:873225854411:ios:eb96f776359b7e3f94ea4e',
    messagingSenderId: '873225854411',
    projectId: 'dorun-server',
    databaseURL: 'https://dorun-server-default-rtdb.firebaseio.com',
    storageBucket: 'dorun-server.appspot.com',
    iosClientId: '873225854411-aappmrv1av2pgvbsf03ef3pm497vegu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorunDorun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-ugZV8C1Rq7GbSlrETdNFhA2T4iv02E',
    appId: '1:873225854411:ios:eb96f776359b7e3f94ea4e',
    messagingSenderId: '873225854411',
    projectId: 'dorun-server',
    databaseURL: 'https://dorun-server-default-rtdb.firebaseio.com',
    storageBucket: 'dorun-server.appspot.com',
    iosClientId: '873225854411-aappmrv1av2pgvbsf03ef3pm497vegu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorunDorun',
  );
}
